spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_notify_fireBase
    username: teandz
    password: Tuananhvpn123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: ${JPA_OPEN_IN_VIEW:false}
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#        generate_statistics: true
        jdbc.batch_size: 100
        order_inserts: true
        order_updates: true
        continue-on-error: true
#        format_sql: true
#
#  kafka:
#    bootstrap-servers: 172.16.0.6:9092
#    topics:
#      config:
#        num-partitions: ${KAFKA_NUM_PARTITIONS:3}
#        replication-factor: ${KAFKA_REPLICATION_FACTOR:1}
#        retention-ms: ${KAFKA_RETENTION_MS:2592000000}
#      names:
#        event-log: ${KAFKA_TOPIC_EVENT_LOG:wiinvent.vtpost.vtpost.gami.event_log.test}
#        task-completion: ${KAFKA_TOPIC_TASK_COMPLETION:wiinvent.vtpost.vtpost.gami.task_completion.test}
#
#
#app:
#  firebase-configuration-file: tean-app-20d37-firebase-adminsdk-vw3ll-d6a966162a.json
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/lab
#    username: tean
#    password: 123456
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    open-in-view: ${JPA_OPEN_IN_VIEW:false}
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        #        generate_statistics: true
#        jdbc.batch_size: 100
#        order_inserts: true
#        order_updates: true
#        continue-on-error: true
#        format_sql: true